//
// Created by Liam on 12/29/21.
//

#ifndef ROCKETMQ_CLIENT_CPP_COMMONCONSTANTS_H
#define DEFAULT_TIMEOUT_MILLISECOND 30000
// 30s
#define TCP_CONNECT_TIMEOUT_MILLISECOND 30000
// 3s
#define TCP_TRANSPORT_TRY_LOCK_TIMEOUT_SECOND 3
// 30s
#define GET_TOPIC_ROUTE_INFO_TIMEOUT_MILLISCOND 30000
#define ROCKETMQ_CLIENT_CPP_COMMONCONSTANTS_H

#endif  // ROCKETMQ_CLIENT_CPP_COMMONCONSTANTS_H
